

build:
  version: '2.0'

accounts:
  message: "Welcome to EazyBank accounts production related webhook APIs "
  contactDetails:
    name: "sree - Developer"
    email: "sree@eazybank.com"
  onCallSupport:
    - 420
    - (555) 523-1345
